### PR TITLE
pip install for Briar IDS, try #2.

### PR DESCRIPTION
**Pull request by ebel**
We will need to update wiki docs after approved, I could not do with fork. Not sure what happened to committers, used my work account for a bit, I fixed. Also, had to add sudo for some of the scripts, I will look at more later to see if I really need. Let me know if you have any questions or find some probs.
I had to rearrange some files and organization of project, let me know if prob.
To install:
1. Install pip (should be on raspi by default)
2. Install = 'pip install ~/BriarIDS/dist/briar-0.1.27.tar.gz'
3. Check verision with 'pip freeze'
4. To open briar gui = 'briar'
5. Use as normal
6. To get new version, `pip install --upgrade briar`
7. Can do a 'pip freeze' to check version whenever

- Create account on pypi, follow this blog example:
	http://peterdowns.com/posts/first-time-with-pypi.html  <== i will do this once its merged into master.

### CODE REVIEW

**Comment by g3tsyst3m** [comment]
cool.  would you mind correcting the branch conflicts before I test?  If this is something I need to do I'm happy to help as well.  thx

**Comment by ebel** [comment]
Yeah it wouldn't let me. Said I don't have write access and couldn't see the conflicts

**Comment by g3tsyst3m** [comment]
I am currently reviewing the new changes you've made tyler.  I like what I see :)
everything installed just fine.  One item we will need to add into the wiki first thing is: 
**sudo python setup.py install** BEFORE starting briar.

I have granted you editing privileges to the WIKI.  let me know if you are able to edit it now
I will let you know once I finish reviewing the pull request changes/additions.  

for users on the current briar version, we will probably need to provide instructions on how to move over to the pip install version.  either that, or let them know the briar_ids.py is located here now:
BriarIDS/briarids$ sudo python briar_ids.py
we could add an instructions.txt file or something

Once they open briarids, it will update their git repo to this version and their familiar briar_ids.py will not be visible anymore which could be confusing to our current briar users.
I hope that makes sense and thanks for your hard work with this.

**Comment by ebel** [comment]
ok, I will look at everything tonight.

**Comment by ebel** [comment]
That email i got for wiji access gave me a 404 the other day. Just checked,
and I cannot edit the wiki.

**Comment by g3tsyst3m** [comment]
I just sent you a link to your email.  Once you accept that invitation you should have collaboration access to the wiki
thx
Robbie

**Comment by ebel** [comment]
Ill have the wiki stuff done by tomorrow night. Been swamped.

**Comment by g3tsyst3m** [comment]
DONE!  thanks for your hard work on this Tyler.
Now, to the WIKI for install tips and adjustments :)

**Comment by ebel** [comment]
Thanks, WIKI is in progress, will update soonn.

**Pull request merged**
