### PR TITLE
pip install for Briar IDS.

### PR DESCRIPTION
**Pull request by ebel**
We will need to update wiki docs after approved, I could not do with fork. Not sure what happened to committers, used my work account for a bit, I fixed. Also, had to add sudo for some of the scripts, I will look at more later to see if I really need. Let me know if you have any questions or find some probs.
I had to rearrange some files and organization of project, let me know if prob.
To install:
1. Install pip (should be on raspi by default)
2. Install = 'pip install briar_ids'
3. Check verision with 'pip freeze'
4. To open briar gui = 'briar'
5. Use as normal
6. To get new version, `pip install --upgrade briar`
7. Can do a 'pip freeze' to check version whenever

- Create account on pypi, follow this blog example:
	http://peterdowns.com/posts/first-time-with-pypi.html  <== i will do this once its merged into master.

### CODE REVIEW

**Comment by ebel** [comment]
I merged latest into my fork, I will look at more for these conflicts...again.

**Comment by ebel** [comment]
Sloppy. Going to fix and remake.

**Comment by g3tsyst3m** [comment]
I cannot seem to get this going.  I'm guessing you may still be working on this.  Any thoughts?

pip install briar_ids
Collecting briar_ids
  Could not find a version that satisfies the requirement briar_ids (from versions: )
No matching distribution found for briar_ids
pip search briar
Briareus (0.6.3)  - UNKNOWN

**Comment by ebel** [comment]
I am redoing the pull request, it had some probs. I should get it out
tonight/early tomorrow.

**Comment by g3tsyst3m** [comment]
No problem, sounds good

**Pull request closed without merging**
