### PR TITLE
PEP8/PEP257 cleanup

### PR DESCRIPTION
**Pull request by ebel**
- Renamed module names 
 - Renamed a couple of functions 
 - Added doc strings to modules, classes, and functions
 - Deleted commented out code
 - Modified some basic formatting of code
 - Test it still loads and UI works on a raspi 3

### CODE REVIEW

**Comment by g3tsyst3m** [comment]
thanks Tyler.  Everything looks to be in order.  I will test the changes tonight and assuming everything cooperates, approve the push :)

**Comment by g3tsyst3m** [comment]
Tyler would you mind updating your fork and then pushing these commits again?  It seems there is a merge conflict, probably from where I pushed an update around the time you were working on these commits.
thanks
Robbie

**Comment by ebel** [comment]
My bad, Ill watch out for that next time. Should be good now.

**Comment by g3tsyst3m** [comment]
not a problem.  thanks for the edits!

**Pull request merged**
